### ISSUE TITLE
en-dash / em-dash

### ISSUE THREAD

**Issue by pfasante** [dspinellis/latex-advice#5]
In the example for the em-dash you use it with spaces around:
`The Entity-Relationship Model --- Toward a Unified View of Data`

As far as I know the em-dash should be used without spaces around (see eg. the Chicago Manual of Style http://chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0002.html) or instead use an en-dash with spaces (see eg. Bringhurst’s The Elements of Typographic Style).
I once read somewhere that the em-dash is more American style, while the spaced en-dash is more Britain style, but I cannot find this source anymore.

**Comment by dspinellis** [comment]
You're, right regarding the style differences; see http://apvschicago.com/2011/05/em-dashes-and-ellipses-closed-or-spaced.html
