### ISSUE TITLE
SCons for build automation

### ISSUE THREAD

**Issue by NikosAlexandris** [dspinellis/latex-advice#8]
If omitting [SCons](https://scons.org/) from [the list of build-automation utilities](https://github.com/dspinellis/latex-advice#automate-the-document-build), is not on-purpose, please consider adding it. SCons supports for building TeX and LaTeX documents. See also:
* https://github.com/SCons/scons/wiki/LatexSupport
* https://tex.stackexchange.com/a/26573/8272.

**Comment by dspinellis** [comment]
Thanks!  Given that the list offers many possibilities, rather than one, let's add it. Do you want to submit a PR?

**Comment by NikosAlexandris** [comment]
Done.
